import { Question } from '@/types';

export const questions: Question[] = [
  // Category 1: Preference Choice (1-30)
  { id: 1, category: 'preference', type: 'binary', text: '휴가를 계획할 때', options: [{ id: 'A', text: '계획을 철저히 세운다' }, { id: 'B', text: '현지에서 즉흥적으로 결정한다' }], tags: ['planning', 'risk', 'intuition'] },
  { id: 2, category: 'preference', type: 'binary', text: '문제를 해결할 때', options: [{ id: 'A', text: '빠르게 결정한다' }, { id: 'B', text: '충분히 조사 후 결정한다' }], tags: ['intuition', 'patience', 'decision'] },
  { id: 3, category: 'preference', type: 'binary', text: '여행을 간다면', options: [{ id: 'A', text: '자연 중심' }, { id: 'B', text: '도시 중심' }], tags: ['preference', 'lifestyle'] },
  { id: 4, category: 'preference', type: 'binary', text: '업무 스타일', options: [{ id: 'A', text: '멀티태스킹' }, { id: 'B', text: '한 번에 하나 집중' }], tags: ['focus', 'multitasking', 'consistency'] },
  { id: 5, category: 'preference', type: 'binary', text: '리스크 있는 투자', options: [{ id: 'A', text: '높은 수익 가능성 선택' }, { id: 'B', text: '안정적인 선택' }], tags: ['risk', 'decision'] },
  { id: 6, category: 'preference', type: 'binary', text: '모임에서 나는', options: [{ id: 'A', text: '먼저 말한다' }, { id: 'B', text: '먼저 듣는다' }], tags: ['social', 'communication'] },
  { id: 7, category: 'preference', type: 'binary', text: '친구 관계', options: [{ id: 'A', text: '소수 깊은 관계' }, { id: 'B', text: '넓은 관계' }], tags: ['social', 'relationship'] },
  { id: 8, category: 'preference', type: 'binary', text: '정보를 얻을 때', options: [{ id: 'A', text: '직관적으로 판단' }, { id: 'B', text: '데이터를 확인' }], tags: ['intuition', 'data', 'decision'] },
  { id: 9, category: 'preference', type: 'binary', text: '새로운 음식', options: [{ id: 'A', text: '바로 시도' }, { id: 'B', text: '검증 후 시도' }], tags: ['risk', 'openness'] },
  { id: 10, category: 'preference', type: 'binary', text: '팀 프로젝트', options: [{ id: 'A', text: '리더 역할' }, { id: 'B', text: '지원 역할' }], tags: ['social', 'leadership'] },
  { id: 11, category: 'preference', type: 'binary', text: '새로운 기술', options: [{ id: 'A', text: '먼저 써본다' }, { id: 'B', text: '안정화 후 사용' }], tags: ['risk', 'innovation'] },
  { id: 12, category: 'preference', type: 'binary', text: '문제가 생겼을 때', options: [{ id: 'A', text: '바로 해결 시도' }, { id: 'B', text: '상황을 먼저 관찰' }], tags: ['intuition', 'patience', 'reaction'] },
  { id: 13, category: 'preference', type: 'binary', text: '결정을 내릴 때', options: [{ id: 'A', text: '감정 영향 큼' }, { id: 'B', text: '논리 영향 큼' }], tags: ['emotion', 'logic', 'decision'] },
  { id: 14, category: 'preference', type: 'binary', text: '중요한 선택', options: [{ id: 'A', text: '빠르게' }, { id: 'B', text: '오래 고민' }], tags: ['intuition', 'patience', 'consistency'], pairedQuestionId: 2 },
  { id: 15, category: 'preference', type: 'binary', text: '선물 선택', options: [{ id: 'A', text: '실용성' }, { id: 'B', text: '감정적 의미' }], tags: ['emotion', 'logic'] },
  { id: 16, category: 'preference', type: 'binary', text: '뉴스 소비', options: [{ id: 'A', text: '다양한 관점' }, { id: 'B', text: '신뢰하는 소수 매체' }], tags: ['information', 'openness'] },
  { id: 17, category: 'preference', type: 'binary', text: '돈 사용', options: [{ id: 'A', text: '경험에 투자' }, { id: 'B', text: '자산에 투자' }], tags: ['risk', 'value', 'future'] },
  { id: 18, category: 'preference', type: 'binary', text: '성공 기준', options: [{ id: 'A', text: '성취' }, { id: 'B', text: '안정' }], tags: ['value', 'risk'] },
  { id: 19, category: 'preference', type: 'binary', text: '새로운 사람', options: [{ id: 'A', text: '먼저 다가간다' }, { id: 'B', text: '기다린다' }], tags: ['social', 'openness'] },
  { id: 20, category: 'preference', type: 'binary', text: '정보 판단', options: [{ id: 'A', text: '직감' }, { id: 'B', text: '근거' }], tags: ['intuition', 'logic'], pairedQuestionId: 8, reverseQuestion: true },
  { id: 21, category: 'preference', type: 'binary', text: '휴식', options: [{ id: 'A', text: '혼자' }, { id: 'B', text: '사람들과' }], tags: ['social', 'introvert', 'extrovert'] },
  { id: 22, category: 'preference', type: 'binary', text: '학습 방식', options: [{ id: 'A', text: '실습' }, { id: 'B', text: '이론' }], tags: ['learning', 'intuition'] },
  { id: 23, category: 'preference', type: 'binary', text: '갈등 상황', options: [{ id: 'A', text: '직접 해결' }, { id: 'B', text: '중재 요청' }], tags: ['social', 'conflict', 'principle'] },
  { id: 24, category: 'preference', type: 'binary', text: '문제 해결', options: [{ id: 'A', text: '새로운 방법' }, { id: 'B', text: '기존 방법' }], tags: ['innovation', 'risk', 'consistency'] },
  { id: 25, category: 'preference', type: 'binary', text: '시간 관리', options: [{ id: 'A', text: '유연' }, { id: 'B', text: '엄격' }], tags: ['planning', 'flexibility'] },
  { id: 26, category: 'preference', type: 'binary', text: '선택 기준', options: [{ id: 'A', text: '감정' }, { id: 'B', text: '효율' }], tags: ['emotion', 'logic', 'consistency'], pairedQuestionId: 13, reverseQuestion: true },
  { id: 27, category: 'preference', type: 'binary', text: '협업', options: [{ id: 'A', text: '토론 선호' }, { id: 'B', text: '개인 작업 선호' }], tags: ['social', 'collaboration'] },
  { id: 28, category: 'preference', type: 'binary', text: '압박 상황', options: [{ id: 'A', text: '집중 증가' }, { id: 'B', text: '실수 증가' }], tags: ['stress', 'performance'] },
  { id: 29, category: 'preference', type: 'binary', text: '목표 설정', options: [{ id: 'A', text: '큰 목표' }, { id: 'B', text: '작은 목표' }], tags: ['ambition', 'risk', 'planning'] },
  { id: 30, category: 'preference', type: 'binary', text: '의사결정', options: [{ id: 'A', text: '직관' }, { id: 'B', text: '계산' }], tags: ['intuition', 'logic', 'consistency'], pairedQuestionId: 2, reverseQuestion: true },

  // Category 2: Cognitive Style (31-50)
  { id: 31, category: 'cognitive', type: 'binary', text: '정보가 부족한 상황', options: [{ id: 'A', text: '추측하고 행동' }, { id: 'B', text: '정보 수집' }], tags: ['intuition', 'patience', 'risk'] },
  { id: 32, category: 'cognitive', type: 'binary', text: '예상치 못한 상황', options: [{ id: 'A', text: '흥미롭다' }, { id: 'B', text: '불안하다' }], tags: ['openness', 'risk', 'emotion'] },
  { id: 33, category: 'cognitive', type: 'binary', text: '누군가 도움 요청', options: [{ id: 'A', text: '즉시 도움' }, { id: 'B', text: '상황 확인' }], tags: ['empathy', 'social', 'intuition'] },
  { id: 34, category: 'cognitive', type: 'binary', text: '실수 발생', options: [{ id: 'A', text: '빠르게 수정' }, { id: 'B', text: '원인 분석' }], tags: ['reaction', 'patience', 'learning'] },
  { id: 35, category: 'cognitive', type: 'binary', text: '시간 압박', options: [{ id: 'A', text: '직감 사용' }, { id: 'B', text: '분석 시도' }], tags: ['intuition', 'stress', 'decision'] },
  { id: 36, category: 'cognitive', type: 'binary', text: '사람 판단', options: [{ id: 'A', text: '첫인상 중요' }, { id: 'B', text: '시간이 중요' }], tags: ['intuition', 'social', 'consistency'] },
  { id: 37, category: 'cognitive', type: 'binary', text: '새로운 규칙', options: [{ id: 'A', text: '바로 적용' }, { id: 'B', text: '검토 후' }], tags: ['principle', 'flexibility', 'consistency'] },
  { id: 38, category: 'cognitive', type: 'binary', text: '협상 상황', options: [{ id: 'A', text: '양보' }, { id: 'B', text: '설득' }], tags: ['social', 'principle', 'flexibility'] },
  { id: 39, category: 'cognitive', type: 'binary', text: '스트레스 상황', options: [{ id: 'A', text: '행동' }, { id: 'B', text: '생각' }], tags: ['reaction', 'intuition', 'stress'] },
  { id: 40, category: 'cognitive', type: 'binary', text: '불확실성', options: [{ id: 'A', text: '받아들임' }, { id: 'B', text: '회피' }], tags: ['risk', 'openness', 'flexibility'] },
  { id: 41, category: 'cognitive', type: 'binary', text: '결정 후', options: [{ id: 'A', text: '후회 없음' }, { id: 'B', text: '재검토' }], tags: ['consistency', 'patience', 'decision'] },
  { id: 42, category: 'cognitive', type: 'binary', text: '타인의 의견', options: [{ id: 'A', text: '중요' }, { id: 'B', text: '참고 정도' }], tags: ['social', 'principle', 'independence'] },
  { id: 43, category: 'cognitive', type: 'binary', text: '논쟁 상황', options: [{ id: 'A', text: '감정 표현' }, { id: 'B', text: '논리 표현' }], tags: ['emotion', 'logic', 'social'] },
  { id: 44, category: 'cognitive', type: 'binary', text: '정보 해석', options: [{ id: 'A', text: '빠른 패턴 인식' }, { id: 'B', text: '단계적 분석' }], tags: ['intuition', 'patience', 'learning'] },
  { id: 45, category: 'cognitive', type: 'binary', text: '실패 경험', options: [{ id: 'A', text: '교훈' }, { id: 'B', text: '좌절' }], tags: ['resilience', 'learning', 'emotion'] },
  { id: 46, category: 'cognitive', type: 'binary', text: '문제 해결', options: [{ id: 'A', text: '창의' }, { id: 'B', text: '구조' }], tags: ['creativity', 'structure', 'innovation'] },
  { id: 47, category: 'cognitive', type: 'binary', text: '목표 달성', options: [{ id: 'A', text: '동기' }, { id: 'B', text: '시스템' }], tags: ['motivation', 'planning', 'consistency'] },
  { id: 48, category: 'cognitive', type: 'binary', text: '책 선택', options: [{ id: 'A', text: '소설' }, { id: 'B', text: '논픽션' }], tags: ['emotion', 'logic', 'learning'] },
  { id: 49, category: 'cognitive', type: 'binary', text: '의사결정', options: [{ id: 'A', text: '사람 중심' }, { id: 'B', text: '결과 중심' }], tags: ['empathy', 'utilitarian', 'principle'] },
  { id: 50, category: 'cognitive', type: 'binary', text: '상황 판단', options: [{ id: 'A', text: '빠른 직관' }, { id: 'B', text: '깊은 분석' }], tags: ['intuition', 'patience', 'consistency'] },

  // Category 3: Moral Dilemma (51-70)
  { id: 51, category: 'moral', type: 'binary', text: '기찻길 문제', subText: '기차가 5명을 향해 달려간다. 레버를 당기면 기차가 방향을 바꿔 1명만 희생된다.', options: [{ id: 'A', text: '레버를 당긴다 (1명 희생, 5명 구조)' }, { id: 'B', text: '아무것도 하지 않는다 (5명 희생)' }], tags: ['utilitarian', 'principle', 'morality', 'action'], animationType: 'trolley_switch' },
  { id: 52, category: 'moral', type: 'binary', text: '푸시 기찻길 문제', subText: '다리 위에서 큰 사람을 밀면 기차가 멈춰 5명이 산다.', options: [{ id: 'A', text: '밀어서 멈춘다 (1명 희생, 5명 구조)' }, { id: 'B', text: '아무것도 하지 않는다 (5명 희생)' }], tags: ['utilitarian', 'principle', 'morality', 'direct_action'], animationType: 'trolley_push', pairedQuestionId: 51 },
  { id: 53, category: 'moral', type: 'binary', text: '장기 이식 딜레마', subText: '의사가 한 명을 희생하면 다섯 명을 살릴 수 있다.', options: [{ id: 'A', text: '희생 허용' }, { id: 'B', text: '거부' }], tags: ['utilitarian', 'principle', 'morality'], pairedQuestionId: 51 },
  { id: 54, category: 'moral', type: 'binary', text: '자율주행차 문제', subText: '자율주행차가 사고를 피할 수 없다. 어떤 선택이 우선되어야 하는가?', options: [{ id: 'A', text: '승객 보호' }, { id: 'B', text: '보행자 보호' }], tags: ['utilitarian', 'principle', 'morality', 'risk'] },
  { id: 55, category: 'moral', type: 'multiple', text: '구조 우선순위', subText: '불 속에서 먼저 구할 대상을 선택하라.', options: [{ id: 'A', text: '어린이' }, { id: 'B', text: '노인' }, { id: 'C', text: '친구' }, { id: 'D', text: '낯선 사람' }], tags: ['empathy', 'social', 'morality', 'principle'] },
  { id: 56, category: 'moral', type: 'binary', text: '거짓말 문제', subText: '거짓말로 누군가를 구할 수 있다.', options: [{ id: 'A', text: '거짓말을 한다' }, { id: 'B', text: '진실을 말한다' }], tags: ['principle', 'utilitarian', 'morality'] },
  { id: 57, category: 'moral', type: 'binary', text: '친구 범죄', subText: '친구가 범죄를 저질렀다.', options: [{ id: 'A', text: '신고한다' }, { id: 'B', text: '숨긴다' }], tags: ['principle', 'social', 'morality', 'empathy'] },
  { id: 58, category: 'moral', type: 'binary', text: '생존 딜레마', subText: '식량이 부족한 생존 상황이다.', options: [{ id: 'A', text: '공정하게 분배' }, { id: 'B', text: '일부 희생으로 나머지 생존' }], tags: ['utilitarian', 'principle', 'morality', 'risk'] },
  { id: 59, category: 'moral', type: 'binary', text: 'AI 의사', subText: 'AI가 인간보다 정확하게 진단한다. 의사 결정을 누가 해야 하는가?', options: [{ id: 'A', text: 'AI가 결정' }, { id: 'B', text: '인간이 결정' }], tags: ['principle', 'utilitarian', 'technology'] },
  { id: 60, category: 'moral', type: 'binary', text: '기억 삭제', subText: '트라우마를 삭제하면 더 행복한 삶을 살 수 있다.', options: [{ id: 'A', text: '삭제한다' }, { id: 'B', text: '유지한다' }], tags: ['principle', 'happiness', 'identity'] },
  { id: 61, category: 'moral', type: 'binary', text: '복제 인간', subText: '복제된 인간은 원본과 같은 권리를 가져야 하는가?', options: [{ id: 'A', text: '동일한 권리' }, { id: 'B', text: '제한된 권리' }], tags: ['principle', 'empathy', 'identity', 'morality'] },
  { id: 62, category: 'moral', type: 'binary', text: '가난한 사람 도둑질', subText: '가난한 사람이 생존을 위해 도둑질하는 것은 허용되는가?', options: [{ id: 'A', text: '허용된다' }, { id: 'B', text: '불가하다' }], tags: ['principle', 'empathy', 'morality', 'utilitarian'] },
  { id: 63, category: 'moral', type: 'binary', text: '개인정보', subText: '공공 안전을 위해 개인정보를 공유해야 하는가?', options: [{ id: 'A', text: '안전을 위해 공유' }, { id: 'B', text: '개인 보호 우선' }], tags: ['principle', 'social', 'risk', 'morality'] },
  { id: 64, category: 'moral', type: 'binary', text: '감시 사회', subText: '정부 감시를 허용하면 범죄가 줄지만 자유가 줄어든다.', options: [{ id: 'A', text: '범죄 감소 우선' }, { id: 'B', text: '자유 보호 우선' }], tags: ['principle', 'social', 'risk', 'morality'] },
  { id: 65, category: 'moral', type: 'binary', text: '공정 vs 효율', subText: '자원 배분에서 무엇이 더 중요한가?', options: [{ id: 'A', text: '공정성' }, { id: 'B', text: '효율성' }], tags: ['principle', 'utilitarian', 'morality'] },
  { id: 66, category: 'moral', type: 'binary', text: '생명 연장 기술', subText: '생명 연장 기술이 개발된다면?', options: [{ id: 'A', text: '모든 사람에게 제공' }, { id: 'B', text: '제한된 접근' }], tags: ['principle', 'utilitarian', 'social', 'morality'] },
  { id: 67, category: 'moral', type: 'binary', text: 'AI 군사 사용', subText: 'AI를 군사 목적으로 사용하는 것은?', options: [{ id: 'A', text: '허용' }, { id: 'B', text: '금지' }], tags: ['principle', 'morality', 'technology', 'risk'] },
  { id: 68, category: 'moral', type: 'binary', text: '친구 vs 규칙', subText: '친구를 위해 규칙을 어길 수 있는가?', options: [{ id: 'A', text: '친구 우선' }, { id: 'B', text: '규칙 준수' }], tags: ['principle', 'social', 'empathy', 'morality'] },
  { id: 69, category: 'moral', type: 'binary', text: '시간 여행', subText: '과거로 돌아가 한 명을 희생해 많은 사람을 구할 수 있다.', options: [{ id: 'A', text: '과거를 바꾼다' }, { id: 'B', text: '현재를 유지' }], tags: ['utilitarian', 'principle', 'morality'] },
  { id: 70, category: 'moral', type: 'binary', text: '행복 약', subText: '모든 사람을 행복하게 하는 약이 있다면?', options: [{ id: 'A', text: '사용한다' }, { id: 'B', text: '거부한다' }], tags: ['utilitarian', 'principle', 'happiness', 'identity'] },

  // Category 4: Interactive Action (71-85)
  { id: 71, category: 'action', type: 'action_click', text: '긴급 대응 문제', subText: '위기 상황이 발생했다. 어떤 행동을 가장 먼저 하겠는가?', options: [{ id: 'A', text: '즉시 구조 요청' }, { id: 'B', text: '현장 직접 확인' }, { id: 'C', text: '주변 사람 도움 요청' }], tags: ['reaction', 'social', 'intuition', 'empathy'], animationType: 'click_priority' },
  { id: 72, category: 'action', type: 'action_drag', text: '자원 배분', subText: '100 포인트를 배분하세요.', options: [{ id: 'A', text: '가족' }, { id: 'B', text: '친구' }, { id: 'C', text: '낯선 사람' }, { id: 'D', text: '미래의 나' }], tags: ['social', 'value', 'empathy', 'planning'], animationType: 'resource_drag' },
  { id: 73, category: 'action', type: 'action_click', text: '정보 우선순위', subText: '여러 뉴스 카드 중 가장 먼저 클릭하는 것은?', options: [{ id: 'A', text: '경제 뉴스' }, { id: 'B', text: '사회 이슈' }, { id: 'C', text: '스포츠' }, { id: 'D', text: '기술 뉴스' }], tags: ['priority', 'information', 'interest'], animationType: 'click_priority' },
  { id: 74, category: 'action', type: 'action_timer', text: '압박 선택', subText: '5초 안에 선택하세요!', options: [{ id: 'A', text: '안전' }, { id: 'B', text: '자유' }], tags: ['intuition', 'stress', 'reaction', 'decision'], animationType: 'timer_choice', timeLimit: 5 },
  { id: 75, category: 'action', type: 'action_click', text: '위험 선택 게임', subText: '어떤 옵션을 선택하겠는가?', options: [{ id: 'A', text: '50% 확률로 100점' }, { id: 'B', text: '확정 40점' }], tags: ['risk', 'decision', 'intuition'] },
  { id: 76, category: 'action', type: 'action_drag', text: '신뢰 게임', subText: '상대방에게 얼마를 보내겠는가? (0-100점)', options: [{ id: 'A', text: '0-25점 (낮음)' }, { id: 'B', text: '25-50점 (중간)' }, { id: 'C', text: '50-75점 (높음)' }, { id: 'D', text: '75-100점 (완전 신뢰)' }], tags: ['social', 'trust', 'risk', 'empathy'], animationType: 'resource_drag' },
  { id: 77, category: 'action', type: 'binary', text: '협력 게임', subText: '상대방도 같은 선택을 한다고 가정할 때', options: [{ id: 'A', text: '협력 (서로 이익)' }, { id: 'B', text: '배신 (나만 이익)' }], tags: ['social', 'trust', 'principle', 'utilitarian'] },
  { id: 78, category: 'action', type: 'action_click', text: '패턴 찾기', subText: '화면의 패턴을 보고 직관적으로 선택하세요.', options: [{ id: 'A', text: '패턴 A' }, { id: 'B', text: '패턴 B' }, { id: 'C', text: '패턴 C' }], tags: ['intuition', 'pattern', 'perception'], animationType: 'click_priority' },
  { id: 79, category: 'action', type: 'action_click', text: '집중 선택', subText: '여러 버튼 중 특정 색의 버튼만 클릭하세요.', options: [{ id: 'A', text: '파란색' }, { id: 'B', text: '빨간색' }, { id: 'C', text: '초록색' }, { id: 'D', text: '노란색' }], tags: ['focus', 'attention', 'reaction'] },
  { id: 80, category: 'action', type: 'action_timer', text: '주의 분산', subText: '알림이 왔다. 지금 하던 일을 멈추겠는가?', options: [{ id: 'A', text: '즉시 확인' }, { id: 'B', text: '나중에 확인' }], tags: ['focus', 'multitasking', 'priority'], animationType: 'timer_choice', timeLimit: 8 },
  { id: 81, category: 'action', type: 'action_click', text: '순서 선택', subText: '우선순위 순서대로 클릭하세요.', options: [{ id: 'A', text: '건강' }, { id: 'B', text: '돈' }, { id: 'C', text: '관계' }, { id: 'D', text: '시간' }], tags: ['value', 'priority', 'decision'], animationType: 'click_priority' },
  { id: 82, category: 'action', type: 'action_timer', text: '시간 압박 퍼즐', subText: '3초 안에 더 큰 숫자를 선택하세요!', options: [{ id: 'A', text: '742' }, { id: 'B', text: '631' }], tags: ['reaction', 'stress', 'focus'], animationType: 'timer_choice', timeLimit: 3 },
  { id: 83, category: 'action', type: 'action_drag', text: '가치 배분', subText: '하루 시간 24시간을 어떻게 배분하겠는가?', options: [{ id: 'A', text: '일/학업' }, { id: 'B', text: '가족' }, { id: 'C', text: '취미' }, { id: 'D', text: '휴식' }], tags: ['value', 'priority', 'lifestyle'], animationType: 'resource_drag' },
  { id: 84, category: 'action', type: 'action_click', text: '정보 선택', subText: '어떤 뉴스를 먼저 읽겠는가?', options: [{ id: 'A', text: '긍정적인 소식' }, { id: 'B', text: '부정적인 소식' }, { id: 'C', text: '중립적인 정보' }], tags: ['information', 'emotion', 'priority'], animationType: 'click_priority' },
  { id: 85, category: 'action', type: 'action_timer', text: '도덕적 거리감', subText: '5초 안에 선택하세요: 같은 결과지만 다른 표현', options: [{ id: 'A', text: '"한 명을 희생한다"' }, { id: 'B', text: '"다섯 명을 살린다"' }], tags: ['morality', 'framing', 'intuition', 'utilitarian'], animationType: 'timer_choice', timeLimit: 5, pairedQuestionId: 51 },

  // Category 5: Value Ranking (86-100)
  { id: 86, category: 'value', type: 'multiple', text: '가장 중요한 가치', options: [{ id: 'A', text: '자유' }, { id: 'B', text: '안전' }, { id: 'C', text: '공정' }, { id: 'D', text: '행복' }], tags: ['value', 'principle', 'priority'] },
  { id: 87, category: 'value', type: 'multiple', text: '성공의 정의', options: [{ id: 'A', text: '돈' }, { id: 'B', text: '영향력' }, { id: 'C', text: '행복' }, { id: 'D', text: '안정' }], tags: ['value', 'ambition', 'priority'] },
  { id: 88, category: 'value', type: 'multiple', text: '삶의 목표', options: [{ id: 'A', text: '성장' }, { id: 'B', text: '안정' }, { id: 'C', text: '경험' }, { id: 'D', text: '영향' }], tags: ['value', 'ambition', 'lifestyle'] },
  { id: 89, category: 'value', type: 'multiple', text: '시간 사용', options: [{ id: 'A', text: '일' }, { id: 'B', text: '가족' }, { id: 'C', text: '취미' }, { id: 'D', text: '학습' }], tags: ['value', 'priority', 'lifestyle'] },
  { id: 90, category: 'value', type: 'multiple', text: '위험 감수 정도', options: [{ id: 'A', text: '높음 - 모든 것을 건다' }, { id: 'B', text: '중간 - 계산된 위험' }, { id: 'C', text: '낮음 - 안전 우선' }], tags: ['risk', 'decision', 'value'] },
  { id: 91, category: 'value', type: 'multiple', text: '관계 우선순위', options: [{ id: 'A', text: '가족' }, { id: 'B', text: '친구' }, { id: 'C', text: '사회/동료' }], tags: ['social', 'value', 'priority'] },
  { id: 92, category: 'value', type: 'multiple', text: '정보 신뢰 기준', options: [{ id: 'A', text: '전문가 의견' }, { id: 'B', text: '다수의 의견' }, { id: 'C', text: '데이터와 통계' }], tags: ['information', 'principle', 'trust'] },
  { id: 93, category: 'value', type: 'binary', text: '갈등 해결', options: [{ id: 'A', text: '타협' }, { id: 'B', text: '원칙 고수' }], tags: ['principle', 'social', 'flexibility'] },
  { id: 94, category: 'value', type: 'binary', text: '책임 소재', options: [{ id: 'A', text: '개인 책임' }, { id: 'B', text: '집단 책임' }], tags: ['principle', 'social', 'morality'] },
  { id: 95, category: 'value', type: 'binary', text: '공정성의 의미', options: [{ id: 'A', text: '결과 평등' }, { id: 'B', text: '기회 평등' }], tags: ['principle', 'value', 'morality'] },
  { id: 96, category: 'value', type: 'binary', text: '행복의 시간', options: [{ id: 'A', text: '현재 행복 중시' }, { id: 'B', text: '미래 행복 중시' }], tags: ['value', 'future', 'planning'] },
  { id: 97, category: 'value', type: 'binary', text: '노력 vs 재능', options: [{ id: 'A', text: '노력이 더 중요' }, { id: 'B', text: '재능이 더 중요' }], tags: ['value', 'belief', 'effort'] },
  { id: 98, category: 'value', type: 'binary', text: '규칙에 대한 태도', options: [{ id: 'A', text: '엄격하게 지킨다' }, { id: 'B', text: '유연하게 적용' }], tags: ['principle', 'flexibility', 'consistency'] },
  { id: 99, category: 'value', type: 'binary', text: '변화에 대한 태도', options: [{ id: 'A', text: '안정 선호' }, { id: 'B', text: '변화 선호' }], tags: ['risk', 'openness', 'flexibility'] },
  { id: 100, category: 'value', type: 'binary', text: '삶의 방향', options: [{ id: 'A', text: '계획대로 살기' }, { id: 'B', text: '흐름에 따르기' }], tags: ['planning', 'flexibility', 'value'] },
];
